/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vehicles;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author BLAZIN B
 */
public class Vehicle extends javax.swing.JFrame {

    /**
     * Creates new form Vehicle
     */
    public Vehicle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPostalCode = new javax.swing.JTextField();
        jtxtName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtxtAddress = new javax.swing.JTextField();
        jEmail = new javax.swing.JTextField();
        jTelephone = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jTrade = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtReceipt = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jCheckGlobal = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckModified = new javax.swing.JCheckBox();
        jCheckLeather = new javax.swing.JCheckBox();
        jCheckCustomized = new javax.swing.JCheckBox();
        jtxtGlobal = new javax.swing.JTextField();
        jtxtStereo = new javax.swing.JTextField();
        jtxtModified = new javax.swing.JTextField();
        jtxtLeatherInt = new javax.swing.JTextField();
        jtxtCustomized = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jtxtTotal = new javax.swing.JTextField();
        jtxtTax = new javax.swing.JTextField();
        jtxtSubTotal = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jButtonTotal = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3), "Customer's Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Name");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Email");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jPostalCode.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(jPostalCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 350, 40));

        jtxtName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(jtxtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 350, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Address");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Postal Code");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("Telephone");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jtxtAddress.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(jtxtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 350, 40));

        jEmail.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(jEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 350, 40));

        jTelephone.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(jTelephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 350, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 530, 330));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3), "Cars on Sale and Mileage", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Choose a Car");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Trade In a Car");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Car Mileage");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Cost of a Car");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 230, 40));

        jComboBox2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 180, 40));

        jTrade.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTrade.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTrade.setText("0");
        jPanel2.add(jTrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 200, 40));

        jTextField7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField7.setText("0");
        jPanel2.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 190, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 480, 330));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3), "Receipt", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtReceipt.setColumns(20);
        jtxtReceipt.setRows(5);
        jScrollPane1.setViewportView(jtxtReceipt);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 35, 400, 670));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 10, 430, 730));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3), "Car Accessories", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCheckGlobal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jCheckGlobal.setText("Global Positioning System");
        jCheckGlobal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckGlobalActionPerformed(evt);
            }
        });
        jPanel4.add(jCheckGlobal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jCheckBox2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jCheckBox2.setText("Stereo");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        jPanel4.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jCheckModified.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jCheckModified.setText("Modified ");
        jCheckModified.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckModifiedActionPerformed(evt);
            }
        });
        jPanel4.add(jCheckModified, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jCheckLeather.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jCheckLeather.setText("Leather Interior");
        jCheckLeather.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckLeatherActionPerformed(evt);
            }
        });
        jPanel4.add(jCheckLeather, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jCheckCustomized.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jCheckCustomized.setText("Customized Detailing");
        jCheckCustomized.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckCustomizedActionPerformed(evt);
            }
        });
        jPanel4.add(jCheckCustomized, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jtxtGlobal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtxtGlobal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtGlobal.setText("0");
        jPanel4.add(jtxtGlobal, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, 160, 40));

        jtxtStereo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtxtStereo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtStereo.setText("0");
        jPanel4.add(jtxtStereo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 400, 40));

        jtxtModified.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtxtModified.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtModified.setText("0");
        jPanel4.add(jtxtModified, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 330, 40));

        jtxtLeatherInt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtxtLeatherInt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtLeatherInt.setText("0");
        jPanel4.add(jtxtLeatherInt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 270, 40));

        jtxtCustomized.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtxtCustomized.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtCustomized.setText("0");
        jPanel4.add(jtxtCustomized, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 220, 40));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 560, 290));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3), "Calculate Total", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("Total:");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setText("Tax:");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setText("SubTotal:");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jtxtTotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel5.add(jtxtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 240, 60));

        jtxtTax.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel5.add(jtxtTax, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 240, 60));

        jtxtSubTotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel5.add(jtxtSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 240, 60));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, 460, 290));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3), "Calculate Total", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24))); // NOI18N

        jButtonTotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonTotal.setText("Total");
        jButtonTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTotalActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton3.setText("Receipt");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jButtonTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 630, 980, 110));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        jComboBox2.addItem("Select a Car");
        jComboBox2.addItem("Polo");
        jComboBox2.addItem("Audi S3");
        jComboBox2.addItem("VW Amarok");
        jComboBox2.addItem("Mini Cooper");
        
        
        jComboBox1.addItem("Select a Mileage");
        jComboBox1.addItem("100-5000");
        jComboBox1.addItem("5001-20000");
        jComboBox1.addItem("2001-40000");
        jComboBox1.addItem("40001-100000");
        
        jtxtGlobal.setEnabled(false);
        jtxtStereo.setEnabled(false);
        jtxtModified.setEnabled(false);
        jtxtLeatherInt.setEnabled(false);
        jtxtCustomized.setEnabled(false);
        
    }//GEN-LAST:event_formWindowActivated

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
            
        if(jComboBox2.getSelectedItem().equals("Polo"))
        {
            jTextField7.setText("60690");
        }
        
         if(jComboBox2.getSelectedItem().equals("Audi S3"))
        {
            jTextField7.setText("350721");
        }
         
          if(jComboBox2.getSelectedItem().equals("VW Amarok"))
        {
            jTextField7.setText("95000");
        }
          
           if(jComboBox2.getSelectedItem().equals("Mini Cooper"))
        {
            jTextField7.setText("88432");
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
       if (jComboBox1.getSelectedItem().equals("100-5000"))
       {
           jTrade.setText("25000");
       }
       
        if (jComboBox1.getSelectedItem().equals("5001-20000"))
       {
           jTrade.setText("15000");
       }
        
         if (jComboBox1.getSelectedItem().equals("2001-40000"))
       {
           jTrade.setText("10000");
       }
         
          if (jComboBox1.getSelectedItem().equals("40001-100000"))
       {
           jTrade.setText("8000");
       }
    }//GEN-LAST:event_jComboBox1ActionPerformed
private JFrame frame;
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        frame = new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(frame, "Confirm if you want exit", "Vehicle Trading System", JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
       jtxtName.setText(null);
       jtxtAddress.setText(null);
       jPostalCode.setText(null);
       jTelephone.setText(null);
       jEmail.setText(null);
       jtxtTax.setText(null);
       jtxtSubTotal.setText(null);
       jtxtTotal.setText(null);
       jTextField7.setText("0");
       jTrade.setText("0");
       
       jComboBox2.setSelectedItem("Select a Car");
       jComboBox1.setSelectedItem("Select a Mileage");
       
       
        jtxtGlobal.setText("0");
        jtxtStereo.setText("0");
        jtxtModified.setText("0");
        jtxtLeatherInt.setText("0");
        jtxtCustomized.setText("0");
        
        jtxtGlobal.setEnabled(false);
        jtxtStereo.setEnabled(false);
        jtxtModified.setEnabled(false);
        jtxtLeatherInt.setEnabled(false);
        jtxtCustomized.setEnabled(false);
        
        jCheckBox2.setSelected(false);
        jCheckModified.setSelected(false);
        jCheckLeather.setSelected(false);
        jCheckCustomized.setSelected(false);
        jCheckGlobal.setSelected(false);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        if(jCheckBox2.isSelected()== true)
        {
            jtxtStereo.setEnabled(true);
            jtxtStereo.setText("350");
            
        }
        else if(jCheckBox2.isSelected()== false)
        {
            jtxtStereo.setEnabled(false);
            jtxtStereo.setText("0");
        }
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckModifiedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckModifiedActionPerformed
        
        if(jCheckModified.isSelected() == true)
        {
        
            jtxtModified.setText("450");
            jtxtModified.setEnabled(true);
            
        }
        else if (jCheckModified.isSelected() == false)
        {
            
            jtxtModified.setText("0");
            jtxtModified.setEnabled(false);
        }
    }//GEN-LAST:event_jCheckModifiedActionPerformed

    private void jCheckLeatherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckLeatherActionPerformed
        
        if(jCheckLeather.isSelected() == true)
        {
            jtxtLeatherInt.setText("6300");
            jtxtLeatherInt.setEnabled(true);
            
        }
        else if (jCheckLeather.isSelected() == false)
        {
            jtxtLeatherInt.setText("0");
            jtxtLeatherInt.setEnabled(false);
        }
    }//GEN-LAST:event_jCheckLeatherActionPerformed

    private void jCheckCustomizedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckCustomizedActionPerformed
        
        if(jCheckCustomized.isSelected() == true)
        {
            jtxtCustomized.setText("4900");
            jtxtCustomized.setEnabled(true);
        
        }
        else if (jCheckCustomized.isSelected() == false)
        {
            jtxtCustomized.setText("0");
            jtxtCustomized.setEnabled(false);
            
        }
       
    }//GEN-LAST:event_jCheckCustomizedActionPerformed

    private void jCheckGlobalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckGlobalActionPerformed
        
        if(jCheckGlobal.isSelected() == true)
        {
            jtxtGlobal.setText("320");
            jtxtGlobal.setEnabled(true);
        
        }
        else if (jCheckGlobal.isSelected() == false)
        {
            jtxtGlobal.setText("0");
            jtxtGlobal.setEnabled(false);
        }
    }//GEN-LAST:event_jCheckGlobalActionPerformed

    private void jButtonTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTotalActionPerformed
        
        double[] CarCost = new double[12];
        
        CarCost[0] = Double.parseDouble(jtxtStereo.getText());
        CarCost[1] = Double.parseDouble(jtxtModified.getText());
        CarCost[2] = Double.parseDouble(jtxtLeatherInt.getText());
        CarCost[3] = Double.parseDouble(jtxtCustomized.getText());
        CarCost[4] = Double.parseDouble(jtxtGlobal.getText());
        CarCost[5] = Double.parseDouble(jTextField7.getText());
        CarCost[6] = Double.parseDouble(jTrade.getText());
        
        CarCost[7] = CarCost[0] + CarCost[1] + CarCost[2] + CarCost[3] + CarCost[4] + CarCost[5] + CarCost[6];
        
        CarCost[8] = (CarCost[7] * 0.45)/100;
        
        String Tax = String.format("R%.2f", CarCost[8]);
        jtxtTax.setText(Tax);
        
        String SubTotal = String.format("R%.2f", CarCost[7]);
        jtxtSubTotal.setText(SubTotal);
        
        String Total = String.format("R%.2f", CarCost[7] + CarCost[8]);
        jtxtTotal.setText(Total);


        
    }//GEN-LAST:event_jButtonTotalActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       
        
        String name = (jtxtName.getText());
        String address = (jtxtAddress.getText());
        String postalcode = (jPostalCode.getText());
        String telephone = (jTelephone.getText());
        String rTax = (jtxtTax.getText());
        String rSubTotal = (jtxtSubTotal.getText());
        String rTotal = (jtxtTotal.getText());
        String rTradeIn = (jTrade.getText());
        String rSoldCar = (jTextField7.getText());
        
        jtxtReceipt.append("\tCar Dealer system:\n\n"
                +"Name:\t\t\t" + name
                +"\nAddress:\t\t" + address
                +"\nPostalcode:\t\t" + postalcode
                +"\nTelephone:\t\t" + telephone
                +"\nCost of Car:\t\t" + rSoldCar
                +"\nTrade In:\t\t"+ rTradeIn
                +"\nTax:\t\t\t" + rTax
                +"\nSub Total:\t\t"+ rSubTotal
                +"\nTotal:\t\t\t" + rTotal
                +"nTelephone:\t\t"+ telephone
                +"\n\n\tThank you for using Car Systems"
                
        );
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vehicle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonTotal;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckCustomized;
    private javax.swing.JCheckBox jCheckGlobal;
    private javax.swing.JCheckBox jCheckLeather;
    private javax.swing.JCheckBox jCheckModified;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JTextField jEmail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField jPostalCode;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTelephone;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTrade;
    private javax.swing.JTextField jtxtAddress;
    private javax.swing.JTextField jtxtCustomized;
    private javax.swing.JTextField jtxtGlobal;
    private javax.swing.JTextField jtxtLeatherInt;
    private javax.swing.JTextField jtxtModified;
    private javax.swing.JTextField jtxtName;
    private javax.swing.JTextArea jtxtReceipt;
    private javax.swing.JTextField jtxtStereo;
    private javax.swing.JTextField jtxtSubTotal;
    private javax.swing.JTextField jtxtTax;
    private javax.swing.JTextField jtxtTotal;
    // End of variables declaration//GEN-END:variables
}
